### ISSUE TITLE
Can someone share a compiled file for me? 有人能够分享给我一个编译好的文件吗？

### ISSUE THREAD

**Issue by MinaAku** [sun1638650145/Libraries-and-Extensions-for-TensorFlow-for-Apple-Silicon#11]
My trial had to stop at the compile step due to network issues. Can someone share a compiled file for me to install directly? My device is M1pro; TensorFlow 2.9.0

由于网络问题，我的试用不得不在编译的步骤上停止。有人能够分享给我一个编译好的文件以让我直接安装吗？我的设备是 M1pro；TensorFlow 2.9.0

Thanks for any help!
感谢您！

**Comment by sun1638650145** [comment]
你好, 请详细描述你的问题. 如果你需要`TensorFlow v2.9.0`对应的`text`或`addons`的`whl`, 在发布页可自行找到下载.

**Comment by maparent** [comment]
Apple recently released new versions of tensorflow-macos 2.11 and tensorflow-metal 0.7, with which it was possible to compile tensorflow-text with the usual procedure. You can get them here for python [3.9](https://idealoom.org/wheelhouse/tensorflow_text-2.11.0-cp39-cp39-macosx_11_0_arm64.whl) and [3.10](https://idealoom.org/wheelhouse/tensorflow_text-2.11.0-cp310-cp310-macosx_11_0_arm64.whl). Note that it is rather easy to make them crash, depending on other installed packages; but a bare install (with tensorflow-macos, tensorflow-metal and dependencies) seems to work as intended.

**Comment by sun1638650145** [comment]
@maparent Using the `whl` you provided, the following error occurs on Python 3.9, and the previous error remains on Python 3.10. I'm not sure if there is a difference in your environment (`venv` or `conda`) and dependencies between us.
```shell
ImportError: Python version mismatch: module was compiled for Python 3.10, but t he interpreter version is incompatible: 3.9.15 | packaged by conda-forge | (main , Nov 22 2022, 08:48:25)
[Clang 14.0.6 ].
```

**Comment by sun1638650145** [comment]
[There is my latest attempt based on `tensorflow-macos 2.11`](https://github.com/sun1638650145/Libraries-and-Extensions-for-TensorFlow-for-Apple-Silicon/issues/7#issuecomment-1345180093). I think the main problem now is Xcode's `ld`.

**Comment by maparent** [comment]
Getting the same error now, but both worked yesterday. Deeply puzzled. I wonder if there were remains of the bezel build process that enabled it to run. Will look deeper later today.

**Comment by sun1638650145** [comment]
@MinaAku 你在发布页可找到全部版本的`tensorflow-text`的`whl`文件下载.

**Comment by sun1638650145** [comment]
@maparent After confirmation, it was determined that the issues with `tensorflow-text 2.10` and `2.11` were caused by `Apple Clang`. Please use `Xcode 14.3` and `Apple clang version 14.0.3 (clang-1403.0.22.14.1)`.
