### ISSUE TITLE
Plz update tensorflow-text

### ISSUE THREAD

**Issue by pokecheater** [sun1638650145/Libraries-and-Extensions-for-TensorFlow-for-Apple-Silicon#12]
Hello, 

I want to use the newest tensorflow-metal version but with it the dependency- hell starts freaking me out :-D.
I need tensorflow 2.11 for it but tensorflow-text is not compatible with this tensorflow version. As pip states: the latest version that is compatible is tensorflow-text 2.9.
<img width="616" alt="image" src="https://user-images.githubusercontent.com/20928617/218955865-9b454d98-2cb9-494b-bcde-29873844a418.png">

Thx in advance <3.

**Comment by sun1638650145** [comment]
@pokecheater Please follow this [issue](https://github.com/sun1638650145/Libraries-and-Extensions-for-TensorFlow-for-Apple-Silicon/issues/7).
