### ISSUE TITLE
TensorFlow Text for macOS 13

### ISSUE THREAD

**Issue by aaarrti** [sun1638650145/Libraries-and-Extensions-for-TensorFlow-for-Apple-Silicon#13]
Hi, 
thank you so much for these pre-compiled releases!
Do you plan to add `tensorflow_text-*-cp*-cp*-macosx_13_0_arm64.whl` builds?

**Comment by sun1638650145** [comment]
`tensorflow_text-*-cp*-cp*-macosx_11_0_arm64.whl` indicates that the minimum compatible system is `macOS 11`, so `macOS 13` is already supported.
