### ISSUE TITLE
malformed trie child cycle to nodeOffset=0x2 E weak-def symbol not found 

### ISSUE THREAD

**Issue by tuzhucheng** [sun1638650145/Libraries-and-Extensions-for-TensorFlow-for-Apple-Silicon#18]
Hi, thanks so much for creating this repo!

When I installed the provided `tensorflow-text` (`pip install tensorflow-text@https://github.com/sun1638650145/Libraries-and-Extensions-for-TensorFlow-for-Apple-Silicon/releases/download/v2.14/tensorflow_text-2.14.0-cp39-cp39-macosx_11_0_arm64.whl`), it is working as expected.

However, when I tried to compile it myself following instructions at https://github.com/sun1638650145/Libraries-and-Extensions-for-TensorFlow-for-Apple-Silicon/blob/main/tutorials/text/text.md, I get the following error when trying to use it: 

```
../../miniforge3/envs/.../lib/python3.9/site-packages/tensorflow/python/framework/load_library.py:54: in load_op_library
    lib_handle = py_tf.TF_LoadLibrary(library_filename)
E   tensorflow.python.framework.errors_impl.NotFoundError: dlopen(/Users/.../miniforge3/envs/.../lib/python3.9/site-packages/tensorflow_text/python/ops/_regex_split_ops.dylib, 0x0006): malformed trie child, cycle to nodeOffset=0x2
E   weak-def symbol not found '__ZN10tensorflow4text12RegexSplitOp14CachedDelimRE2ERKNSt3__112basic_stringIcNS2_11char_traitsIcEENS2_9allocatorIcEEEE'
```

I wonder if you've seen this error before?

**Comment by sun1638650145** [comment]
@tuzhucheng A similar issue to your problem has also been reported [here](https://github.com/sun1638650145/Libraries-and-Extensions-for-TensorFlow-for-Apple-Silicon/issues/4). I'm now leaning more towards it being a `compiler` and `macOS` issue. Could you provide your detailed information?

**Comment by sun1638650145** [comment]
Here is my `clang` version for your reference.
![截屏2023-10-18 上午11 29 46](https://github.com/sun1638650145/Libraries-and-Extensions-for-TensorFlow-for-Apple-Silicon/assets/47380395/d7eda5b2-6e35-460c-8790-e9115e574b1a)

**Comment by tuzhucheng** [comment]
Thanks for the fast response! I am using the following. Let me try to upgrade it.

```
clang -v
Apple clang version 14.0.0 (clang-1400.0.29.202)
Target: arm64-apple-darwin22.2.0
```

**Comment by sun1638650145** [comment]
I forgot to mention earlier, please remember to clear your previous `bazel` cache.

**Comment by tuzhucheng** [comment]
I verified that clang 15.0.0 works, thanks so much!
