### ISSUE TITLE
tf-text 2.15

### ISSUE THREAD

**Issue by rbasa349** [sun1638650145/Libraries-and-Extensions-for-TensorFlow-for-Apple-Silicon#19]
Hello! Could you update tf-text to 2.15?

![image](https://github.com/sun1638650145/Libraries-and-Extensions-for-TensorFlow-for-Apple-Silicon/assets/116624984/ba8b37ae-f16e-411e-a65c-0c16acdba049)

**Comment by maparent** [comment]
Note that, for python3.11, tensorflow-text builds pretty much out of the box following the README instructions. I built a [wheel](https://idealoom.org/wheelhouse/tensorflow_text-2.15.0-cp311-cp311-macosx_11_0_arm64.whl).
There are build issues (around array templates) with python3.9 and 3.10; and missing dependencies for 3.12.

**Comment by sun1638650145** [comment]
@rbasa349 I'm sorry, I just realized that `tensorflow-text 2.15` has been released. I will be building all the `whl` files soon.

**Comment by sun1638650145** [comment]
@rbasa349 You can now download it from [here](https://github.com/sun1638650145/Libraries-and-Extensions-for-TensorFlow-for-Apple-Silicon/releases/tag/v2.15).
