### ISSUE TITLE
tensorflow 15 not listing GPU

### ISSUE THREAD

**Issue by JuliusNmn** [sun1638650145/Libraries-and-Extensions-for-TensorFlow-for-Apple-Silicon#20]
I installed tensorflow 15 from the releases page like this:
```
pip install https://github.com/sun1638650145/Libraries-and-Extensions-for-TensorFlow-for-Apple-Silicon/releases/download/v2.15/tensorflow-2.15.0-cp311-cp311-macosx_14_0_arm64.whl

```

Tensorflow does not list any cpus:
```
>>> import tensorflow as tf
>>> tf.config.list_physical_devices("GPU")
[]
```

Running on a clean venv with python 3.11.1

**Comment by sun1638650145** [comment]
@JuliusNmn The reason for not recognizing the GPU is that you have not installed `tensorflow-metal`.

**Comment by sun1638650145** [comment]
You haven't responded to this issue for quite some time. I will close this issue.
