### ISSUE TITLE
Build tensorflow-text for linux_aarch64 

### ISSUE THREAD

**Issue by Nitrino** [sun1638650145/Libraries-and-Extensions-for-TensorFlow-for-Apple-Silicon#22]
Hi, thanks for your builds and isnturctions, they are very useful.

The `linux_aarch64` version is required to build `tensorflow` in docker on macOS . 
I built `tenserflow-text` for `linux_aarch64`, maybe attach them to the release page? This will be helpful for anyone who has encountered this

[tensorflow_text-2.15.0-cp39-11-cp39-11-linux_aarch64.whl.zip](https://github.com/sun1638650145/Libraries-and-Extensions-for-TensorFlow-for-Apple-Silicon/files/14083686/tensorflow_text-2.15.0-cp39-11-cp39-11-linux_aarch64.whl.zip)

**Comment by sun1638650145** [comment]
If you wish to submit a Python `whl` file for the `aarch64` architecture, please write a build tutorial (English version will suffice) and initiate a PR. This repository also aims to provide guidance for building methods to everyone.

**Comment by sun1638650145** [comment]
I am not very familiar with the toolchain and compilation differences on `aarch64`. If you think these differences are minimal, you can either modify the existing tutorial for `tensorflow-text`, or choose to write a completely new tutorial. It's entirely up to you.

**Comment by Switc4** [comment]
> Hi, thanks for your builds and isnturctions, they are very useful.
> 
> The `linux_aarch64` version is required to build `tensorflow` in docker on macOS . I built `tenserflow-text` for `linux_aarch64`, maybe attach them to the release page? This will be helpful for anyone who has encountered this
> 
> [tensorflow_text-2.15.0-cp39-11-cp39-11-linux_aarch64.whl.zip](https://github.com/sun1638650145/Libraries-and-Extensions-for-TensorFlow-for-Apple-Silicon/files/14083686/tensorflow_text-2.15.0-cp39-11-cp39-11-linux_aarch64.whl.zip)

Hi, thanks for file, at least i get rid of few errors using this one
but my project needs 2.8.2 text and 2.8.0 tensorflow
I have a lot of errors and cant adapt it , becuase of Keras erros and others one
I was wondering is it possible to make for mine versions whl file? Thank you

**Comment by sun1638650145** [comment]
@Switc4 Please create a new issue. 😊

**Comment by Switc4** [comment]
> @Switc4 Please create a new issue. 😊

done, thank you for replying ;3
