### ISSUE TITLE
what does the "cp310" qualifier mean?

### ISSUE THREAD

**Issue by rbelew** [sun1638650145/Libraries-and-Extensions-for-TensorFlow-for-Apple-Silicon#23]
I see "cp310" vs cp311 vs cp39 in the wheels.
Sorry to be ignorant, but how do these vary?

**Comment by MrDevel0per** [comment]
@rbelew https://stackoverflow.com/questions/37023557/what-does-version-name-cp27-or-cp35-mean-in-python answers this question somewhat. The "CP" stands for CPython, or Python version. The 310 means version `3.10`, and the 311 means version `3.11` of Python.

**Comment by sun1638650145** [comment]
Exactly, as @MrDevel0per mentioned, `cp310` is an abbreviation for `CPython 3.10`, where `CPython` denotes the official Python interpreter.

**Comment by rbelew** [comment]
Only 7 years behind the curve! 

> If you check out the [PEP#425](https://www.python.org/dev/peps/pep-0425/) ...

thanks very much to @sun1638650145  and @MrDevel0per .
