### ISSUE TITLE
sentencepiece_processor does not depend on a module exporting 'third_party/darts_clone/darts.h

### ISSUE THREAD

**Issue by raemisch** [sun1638650145/Libraries-and-Extensions-for-TensorFlow-for-Apple-Silicon#5]
Hello,

following exactly the instructions (w/ python 3.9) I keep getting a compiler error that I don't know how to interpret/resolve.

```
ERROR: /private/var/tmp/_bazel_XXXXX/03c196188fbb5dc38e3a61a403354856/external/com_google_sentencepiece/BUILD.bazel:51:11: Compiling src/normalizer.cc failed: (Exit 1): cc_wrapper.sh failed: error executing command external/local_config_cc/cc_wrapper.sh -U_FORTIFY_SOURCE -fstack-protector -Wall -Wthread-safety -Wself-assign -Wunused-but-set-parameter -Wno-free-nonheap-object -fcolor-diagnostics ... (remaining 70 arguments skipped)
external/com_google_sentencepiece/src/normalizer.cc:25:10: error: module: @com_google_sentencepiece//:sentencepiece_processor does not depend on a module exporting 'third_party/darts_clone/darts.h'
#include "third_party/darts_clone/darts.h"
         ^
1 error generated.
Target //oss_scripts/pip_package:build_pip_package failed to build
Use --verbose_failures to see the command lines of failed build steps.
```

Platform: M1 Pro with Monterey (12.4)

If anyone has an idea where this might come from, any help is greatly appreciated.

**Comment by sun1638650145** [comment]
Building with `bazel` requires a stable network. I am concerned that you are also asking the same problem in the `text` repo, [adding new dependencies in BUILD](https://github.com/tensorflow/text/issues/823#issuecomment-1191862703) is one way; I also suggest that you can try to remove your `bazel` cache and retry the build (remember to make sure the network is stable).

**Comment by sun1638650145** [comment]
Please let me know whether it is successful or not and I will continue to help you.

**Comment by raemisch** [comment]
Thanks a lot for the suggestion! Neither of those made difference, though.
Anyway, I'd suggest to continue this discussion [here](https://github.com/tensorflow/text/issues/823), so as to not have two parallel threads.
