### ISSUE TITLE
Problems installing tensorflow-text after building from scratch

### ISSUE THREAD

**Issue by nilpath** [sun1638650145/Libraries-and-Extensions-for-TensorFlow-for-Apple-Silicon#8]
Hi!

With the guidance of the instructions you've provided (big thanks!) I was able to build a wheel file but something still seems to be not quite right as I'm not able to install it.

When I run `pip install ./*.whl` I get the following error
```
Processing ./tensorflow_text-2.8.1-cp38-cp38-macosx_11_0_arm64.whl
Requirement already satisfied: tensorflow-hub>=0.8.0 in ./env/lib/python3.8/site-packages (from tensorflow-text==2.8.1) (0.12.0)
ERROR: Could not find a version that satisfies the requirement tensorflow<2.9,>=2.8.0 (from tensorflow-text) (from versions: none)
ERROR: No matching distribution found for tensorflow<2.9,>=2.8.0
```

python version: 3.8.10
tensorflow-macos: 2.8.0
tensorflow-metal: 0.5.0

tensorflow-text built from tag v2.8.1

Any thoughts on what might be the problem?

**Comment by nilpath** [comment]
However, using your prebuilt .whl works but I'd rather be able to build it myself if possible.

**Comment by sun1638650145** [comment]
You can try `pip install ./*.whl --no-deps`. The problem seems to be caused by you not modifying the dependencies properly (I'm guessing, you didn't switch branch to `v2.8`).

**Comment by nilpath** [comment]
> You can try `pip install ./*.whl --no-deps`. The problem seems to be caused by you not modifying the dependencies properly (I'm guessing, you didn't switch branch to `v2.8`).

I did a `git checkout tags/v2.8.1` on the tensorflow-text repository but is it better to use the branch?

**Comment by nilpath** [comment]
Using the 2.8 branch worked great!

**Comment by sun1638650145** [comment]
That's great, I'll add an extra tip for everyone to use the corresponding branch when installing.
